var a = 10;
var b = 5;
a += b;
document.write(a);
document.write("<br>");
var a = 10;
var b = 5;
a -= b;
document.write(a);
document.write("<br>");
var a = 10;
var b = 5;
a *= b;
document.write(a);
document.write("<br>");
var a = 10;
var b = 5;
a /= b;
document.write(a);
document.write("<br>");
var a = 10;
var b = 5;
a **= b;
document.write(a);
document.write("<br>");
var a = 10;
var b = 5;
a %= b;
document.write(a);